name:        weather-api
version:     "0.4.3.3"
synopsis:    Weather API implemented in Haskell
description: This library implement generic API for retrieving weather
             by HTTP, and has Google weather API as example.

github:      cvb/hs-weather-api
license:     MIT
author:      Peter
maintainer:  peter@standalone.su
category:    API

library:
  exposed-modules:
    - WeatherApi
    - WeatherApi.WWOnline
  other-modules:
    - WeatherApi.Util
dependencies:
  - base < 5
  - HTTP        == 4000.3.*
  - aeson       == 1.0.*
  - attoparsec  == 0.13.*
  - bytestring  == 0.10.*
  - network     == 2.6.*
  - network-uri == 2.6.*
  - utf8-string == 1.0.*
  - vector      == 0.11.*
